walk:
    targets:
        -
            - 0.0
            - -0.359196
            - 0.579781
            - 0.0
            - 0.098086
            - 0.308372
            - 0.0
        -
            - 0.0
            - -0.582038
            - 1.019772
            - 0.0
            - 0.287171
            - 0.445701
            - 0.0
        -
            - 0.0
            - -0.690299
            - 0.922594
            - 0.0
            - 0.440822
            - 0.300847
            - 0.0
        -
            - 0.0
            - -0.728815
            - 0.621845
            - 0.0
            - 0.428915
            - 0.258969
            - 0.0
        -
            - 0.0
            - -0.810035
            - 0.595651
            - 0.0
            - 0.499926
            - 0.365297
            - 0.0
        -
            - 0.0
            - -0.843916
            - 0.68523
            - 0.0
            - 0.514276
            - 0.370471
            - 0.0
        -
            - 0.0
            - -0.756446
            - 0.6886
            - 0.0
            - 0.318032
            - 0.280341
            - 0.0
        -
            - 0.0
            - -0.564374
            - 0.605937
            - 0.0
            - 0.192158
            - 0.366984
            - 0.0
        -
            - 0.0
            - -0.485168
            - 0.752206
            - 0.0
            - 0.156286
            - 0.339759
            - 0.0
        -
            - 0.0
            - -0.544244
            - 1.014481
            - 0.0
            - 0.114982
            - 0.20586
            - 0.0
        -
            - 0.0
            - -0.713097
            - 1.148456
            - 0.0
            - 0.143726
            - 0.212286
            - 0.0
        -
            - 0.0
            - -0.754273
            - 1.161498
            - 0.0
            - 0.203518
            - 0.352629
            - 0.0
        -
            - 0.0
            - -0.418336
            - 1.200936
            - 0.0
            - 0.229885
            - 0.585618
            - 0.0
        -
            - 0.0
            - -0.21715
            - 1.254785
            - 0.0
            - 0.371628
            - 0.827043
            - 0.0
        -
            - 0.0
            - -0.331069
            - 1.022114
            - 0.0
            - 0.559324
            - 1.16472
            - 0.0
        -
            - 0.0
            - -0.492617
            - 0.817656
            - 0.0
            - 0.407069
            - 1.387953
            - 0.0
        -
            - 0.0
            - -0.503633
            - 0.731413
            - 0.0
            - 0.039137
            - 1.344129
            - 0.0
        -
            - 0.0
            - -0.381115
            - 0.699785
            - 0.0
            - -0.391798
            - 1.349302
            - 0.0
        -
            - 0.0
            - 0.016248
            - 0.930164
            - 0.0
            - -0.69298
            - 1.402355
            - 0.0
        -
            - 0.0
            - 0.271472
            - 1.164701
            - 0.0
            - -0.729628
            - 1.400287
            - 0.0
        -
            - 0.0
            - 0.263161
            - 1.116838
            - 0.0
            - -0.681928
            - 1.283255
            - 0.0
        -
            - 0.0
            - 0.285057
            - 1.075213
            - 0.0
            - -0.530252
            - 1.15695
            - 0.0
        -
            - 0.0
            - 0.299259
            - 1.194303
            - 0.0
            - -0.076294
            - 1.17513
            - 0.0
        -
            - 0.0
            - 0.246115
            - 1.351674
            - 0.0
            - 0.151041
            - 1.054768
            - 0.0
        -
            - 0.0
            - 0.2707
            - 1.416217
            - 0.0
            - 0.078512
            - 0.850872
            - 0.0
        -
            - 0.0
            - 0.18011
            - 1.419254
            - 0.0
            - -0.07037
            - 0.890223
            - 0.0
        -
            - 0.0
            - -0.021636
            - 1.417356
            - 0.0
            - -0.270402
            - 1.144053
            - 0.0
        -
            - 0.0
            - -0.133601
            - 1.399784
            - 0.0
            - -0.359262
            - 1.308031
            - 0.0
        -
            - 0.0
            - -0.369324
            - 1.385335
            - 0.0
            - -0.359378
            - 0.981593
            - 0.0
        -
            - 0.0
            - -0.496594
            - 1.419744
            - 0.0
            - -0.369906
            - 0.401432
            - 0.0
        -
            - 0.0
            - -0.418081
            - 1.433206
            - 0.0
            - -0.35678
            - 0.194495
            - 0.0
        -
            - 0.0
            - -0.526612
            - 1.405714
            - 0.0
            - -0.134477
            - 0.372655
            - 0.0
        -
            - 0.0
            - -0.580642
            - 1.300135
            - 0.0
            - -0.061494
            - 0.471236
            - 0.0
        -
            - 0.0
            - -0.21324
            - 1.070826
            - 0.0
            - -0.481818
            - 0.61082
            - 0.0
        -
            - 0.0
            - 0.266047
            - 1.053788
            - 0.0
            - -0.787649
            - 0.731258
            - 0.0
        -
            - 0.0
            - 0.374019
            - 1.180854
            - 0.0
            - -0.795054
            - 0.568314
            - 0.0
        -
            - 0.0
            - 0.346862
            - 1.268326
            - 0.0
            - -0.611848
            - 0.425041
            - 0.0
        -
            - 0.0
            - 0.461951
            - 1.329034
            - 0.0
            - -0.600251
            - 0.514459
            - 0.0
        -
            - 0.0
            - 0.421431
            - 1.201287
            - 0.0
            - -0.826414
            - 0.533032
            - 0.0
        -
            - 0.0
            - 0.009844
            - 1.184115
            - 0.0
            - -0.875078
            - 0.38185
            - 0.0
        -
            - 0.0
            - -0.333159
            - 1.307011
            - 0.0
            - -0.871954
            - 0.368617
            - 0.0
        -
            - 0.0
            - -0.314019
            - 1.183736
            - 0.0
            - -0.831503
            - 0.452471
            - 0.0
        -
            - 0.0
            - -0.489141
            - 0.855568
            - 0.0
            - -0.655581
            - 0.532209
            - 0.0
        -
            - 0.0
            - -0.579604
            - 0.715877
            - 0.0
            - -0.245026
            - 0.901958
            - 0.0
        -
            - 0.0
            - -0.374579
            - 0.725635
            - 0.0
            - 0.275166
            - 1.206639
            - 0.0
        -
            - 0.0
            - -0.389858
            - 0.839862
            - 0.0
            - 0.423766
            - 1.203327
            - 0.0
        -
            - 0.0
            - -0.625751
            - 1.116453
            - 0.0
            - 0.449132
            - 1.17363
            - 0.0
        -
            - 0.0
            - -0.761352
            - 1.29218
            - 0.0
            - 0.554353
            - 1.041255
            - 0.0
        -
            - 0.0
            - -0.788953
            - 1.247255
            - 0.0
            - 0.48381
            - 0.944565
            - 0.0
        -
            - 0.0
            - -0.688525
            - 1.16547
            - 0.0
            - 0.468015
            - 0.809561
            - 0.0
        -
            - 0.0
            - -0.575245
            - 1.094692
            - 0.0
            - 0.389206
            - 0.443458
            - 0.0
        -
            - 0.0
            - -0.690937
            - 1.10621
            - 0.0
            - 0.212043
            - 0.393009
            - 0.0
        -
            - 0.0
            - -0.833022
            - 1.195924
            - 0.0
            - -0.052902
            - 0.627164
            - 0.0
        -
            - 0.0
            - -0.843336
            - 1.272736
            - 0.0
            - -0.397715
            - 0.701171
            - 0.0
        -
            - 0.0
            - -0.715298
            - 1.23407
            - 0.0
            - -0.519475
            - 0.556992
            - 0.0
        -
            - 0.0
            - -0.355507
            - 1.068229
            - 0.0
            - -0.336142
            - 0.311686
            - 0.0
    kp:
        - 300
        - 390
        - 300
        - 300
        - 390
        - 300

    kd:
        - 30 
        - 39
        - 30
        - 30
        - 39
        - 30
    kp_torso: 480
    kd_torso: 240
    dt: 0.25
    c_d: 1.6
    c_v: 0
    mu: 0.65
    max_torque: 800
    g: -9.8
# target: "body","upperLegBridgeR","lowerLegBridgeR","ankleBridgeR","upperLegBridgeL","lowerLegBridgeL","ankleBridgeL"